/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Account
        //private Account instance;

        public AccountTests()
        {
            // TODO uncomment below to create an instance of Account
            //instance = new Account();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Fact]
        public void AccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" Account
            //Assert.IsType<Account>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }

        /// <summary>
        /// Test the property 'CrmObjectType'
        /// </summary>
        [Fact]
        public void CrmObjectTypeTest()
        {
            // TODO unit test for the property 'CrmObjectType'
        }

        /// <summary>
        /// Test the property 'LastContactedAt'
        /// </summary>
        [Fact]
        public void LastContactedAtTest()
        {
            // TODO unit test for the property 'LastContactedAt'
        }

        /// <summary>
        /// Test the property 'LastContactedType'
        /// </summary>
        [Fact]
        public void LastContactedTypeTest()
        {
            // TODO unit test for the property 'LastContactedType'
        }

        /// <summary>
        /// Test the property 'DoNotContact'
        /// </summary>
        [Fact]
        public void DoNotContactTest()
        {
            // TODO unit test for the property 'DoNotContact'
        }

        /// <summary>
        /// Test the property 'Counts'
        /// </summary>
        [Fact]
        public void CountsTest()
        {
            // TODO unit test for the property 'Counts'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Fact]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }

        /// <summary>
        /// Test the property 'LastContactedBy'
        /// </summary>
        [Fact]
        public void LastContactedByTest()
        {
            // TODO unit test for the property 'LastContactedBy'
        }

        /// <summary>
        /// Test the property 'LastContactedPerson'
        /// </summary>
        [Fact]
        public void LastContactedPersonTest()
        {
            // TODO unit test for the property 'LastContactedPerson'
        }
    }
}
