/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Activity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Activity
        //private Activity instance;

        public ActivityTests()
        {
            // TODO uncomment below to create an instance of Activity
            //instance = new Activity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Activity
        /// </summary>
        [Fact]
        public void ActivityInstanceTest()
        {
            // TODO uncomment below to test "IsType" Activity
            //Assert.IsType<Activity>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'DynamicData'
        /// </summary>
        [Fact]
        public void DynamicDataTest()
        {
            // TODO unit test for the property 'DynamicData'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'OccurredAt'
        /// </summary>
        [Fact]
        public void OccurredAtTest()
        {
            // TODO unit test for the property 'OccurredAt'
        }

        /// <summary>
        /// Test the property 'ResourceId'
        /// </summary>
        [Fact]
        public void ResourceIdTest()
        {
            // TODO unit test for the property 'ResourceId'
        }

        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }

        /// <summary>
        /// Test the property 'StaticData'
        /// </summary>
        [Fact]
        public void StaticDataTest()
        {
            // TODO unit test for the property 'StaticData'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'UserGuid'
        /// </summary>
        [Fact]
        public void UserGuidTest()
        {
            // TODO unit test for the property 'UserGuid'
        }
    }
}
