/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing ActivityStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActivityStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActivityStats
        //private ActivityStats instance;

        public ActivityStatsTests()
        {
            // TODO uncomment below to create an instance of ActivityStats
            //instance = new ActivityStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivityStats
        /// </summary>
        [Fact]
        public void ActivityStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActivityStats
            //Assert.IsType<ActivityStats>(instance);
        }

        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Fact]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }

        /// <summary>
        /// Test the property 'Clicks'
        /// </summary>
        [Fact]
        public void ClicksTest()
        {
            // TODO unit test for the property 'Clicks'
        }

        /// <summary>
        /// Test the property 'Replies'
        /// </summary>
        [Fact]
        public void RepliesTest()
        {
            // TODO unit test for the property 'Replies'
        }

        /// <summary>
        /// Test the property 'UniqueDevices'
        /// </summary>
        [Fact]
        public void UniqueDevicesTest()
        {
            // TODO unit test for the property 'UniqueDevices'
        }

        /// <summary>
        /// Test the property 'UniqueLocations'
        /// </summary>
        [Fact]
        public void UniqueLocationsTest()
        {
            // TODO unit test for the property 'UniqueLocations'
        }

        /// <summary>
        /// Test the property 'Views'
        /// </summary>
        [Fact]
        public void ViewsTest()
        {
            // TODO unit test for the property 'Views'
        }
    }
}
