/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Cadence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CadenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Cadence
        //private Cadence instance;

        public CadenceTests()
        {
            // TODO uncomment below to create an instance of Cadence
            //instance = new Cadence();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Cadence
        /// </summary>
        [Fact]
        public void CadenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Cadence
            //Assert.IsType<Cadence>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'LatestActiveDate'
        /// </summary>
        [Fact]
        public void LatestActiveDateTest()
        {
            // TODO unit test for the property 'LatestActiveDate'
        }

        /// <summary>
        /// Test the property 'TeamCadence'
        /// </summary>
        [Fact]
        public void TeamCadenceTest()
        {
            // TODO unit test for the property 'TeamCadence'
        }

        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [Fact]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }

        /// <summary>
        /// Test the property 'Archived'
        /// </summary>
        [Fact]
        public void ArchivedTest()
        {
            // TODO unit test for the property 'Archived'
        }

        /// <summary>
        /// Test the property 'RemoveBouncesEnabled'
        /// </summary>
        [Fact]
        public void RemoveBouncesEnabledTest()
        {
            // TODO unit test for the property 'RemoveBouncesEnabled'
        }

        /// <summary>
        /// Test the property 'RemoveRepliesEnabled'
        /// </summary>
        [Fact]
        public void RemoveRepliesEnabledTest()
        {
            // TODO unit test for the property 'RemoveRepliesEnabled'
        }

        /// <summary>
        /// Test the property 'OptOutLinkIncluded'
        /// </summary>
        [Fact]
        public void OptOutLinkIncludedTest()
        {
            // TODO unit test for the property 'OptOutLinkIncluded'
        }

        /// <summary>
        /// Test the property 'Draft'
        /// </summary>
        [Fact]
        public void DraftTest()
        {
            // TODO unit test for the property 'Draft'
        }

        /// <summary>
        /// Test the property 'CadenceFunction'
        /// </summary>
        [Fact]
        public void CadenceFunctionTest()
        {
            // TODO unit test for the property 'CadenceFunction'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ExternalIdentifier'
        /// </summary>
        [Fact]
        public void ExternalIdentifierTest()
        {
            // TODO unit test for the property 'ExternalIdentifier'
        }

        /// <summary>
        /// Test the property 'CurrentState'
        /// </summary>
        [Fact]
        public void CurrentStateTest()
        {
            // TODO unit test for the property 'CurrentState'
        }

        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Fact]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'BouncedStage'
        /// </summary>
        [Fact]
        public void BouncedStageTest()
        {
            // TODO unit test for the property 'BouncedStage'
        }

        /// <summary>
        /// Test the property 'Counts'
        /// </summary>
        [Fact]
        public void CountsTest()
        {
            // TODO unit test for the property 'Counts'
        }
    }
}
