/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing CadenceContentHolder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CadenceContentHolderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CadenceContentHolder
        //private CadenceContentHolder instance;

        public CadenceContentHolderTests()
        {
            // TODO uncomment below to create an instance of CadenceContentHolder
            //instance = new CadenceContentHolder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CadenceContentHolder
        /// </summary>
        [Fact]
        public void CadenceContentHolderInstanceTest()
        {
            // TODO uncomment below to test "IsType" CadenceContentHolder
            //Assert.IsType<CadenceContentHolder>(instance);
        }

        /// <summary>
        /// Test the property 'CadenceContent'
        /// </summary>
        [Fact]
        public void CadenceContentTest()
        {
            // TODO unit test for the property 'CadenceContent'
        }
    }
}
