/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing CadenceSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CadenceSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CadenceSettings
        //private CadenceSettings instance;

        public CadenceSettingsTests()
        {
            // TODO uncomment below to create an instance of CadenceSettings
            //instance = new CadenceSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CadenceSettings
        /// </summary>
        [Fact]
        public void CadenceSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CadenceSettings
            //Assert.IsType<CadenceSettings>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'TargetDailyPeople'
        /// </summary>
        [Fact]
        public void TargetDailyPeopleTest()
        {
            // TODO unit test for the property 'TargetDailyPeople'
        }

        /// <summary>
        /// Test the property 'RemoveReplied'
        /// </summary>
        [Fact]
        public void RemoveRepliedTest()
        {
            // TODO unit test for the property 'RemoveReplied'
        }

        /// <summary>
        /// Test the property 'RemoveBounced'
        /// </summary>
        [Fact]
        public void RemoveBouncedTest()
        {
            // TODO unit test for the property 'RemoveBounced'
        }

        /// <summary>
        /// Test the property 'CadenceFunction'
        /// </summary>
        [Fact]
        public void CadenceFunctionTest()
        {
            // TODO unit test for the property 'CadenceFunction'
        }
    }
}
