/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing CadenceContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CadenceContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CadenceContent
        //private CadenceContent instance;

        public CadenceContentTests()
        {
            // TODO uncomment below to create an instance of CadenceContent
            //instance = new CadenceContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CadenceContent
        /// </summary>
        [Fact]
        public void CadenceContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" CadenceContent
            //Assert.IsType<CadenceContent>(instance);
        }

        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

        /// <summary>
        /// Test the property 'SharingSettings'
        /// </summary>
        [Fact]
        public void SharingSettingsTest()
        {
            // TODO unit test for the property 'SharingSettings'
        }

        /// <summary>
        /// Test the property 'StepGroups'
        /// </summary>
        [Fact]
        public void StepGroupsTest()
        {
            // TODO unit test for the property 'StepGroups'
        }
    }
}
