/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing CadenceStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CadenceStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CadenceStats
        //private CadenceStats instance;

        public CadenceStatsTests()
        {
            // TODO uncomment below to create an instance of CadenceStats
            //instance = new CadenceStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CadenceStats
        /// </summary>
        [Fact]
        public void CadenceStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CadenceStats
            //Assert.IsType<CadenceStats>(instance);
        }

        /// <summary>
        /// Test the property 'CadencePeople'
        /// </summary>
        [Fact]
        public void CadencePeopleTest()
        {
            // TODO unit test for the property 'CadencePeople'
        }

        /// <summary>
        /// Test the property 'PeopleActedOnCount'
        /// </summary>
        [Fact]
        public void PeopleActedOnCountTest()
        {
            // TODO unit test for the property 'PeopleActedOnCount'
        }

        /// <summary>
        /// Test the property 'TargetDailyPeople'
        /// </summary>
        [Fact]
        public void TargetDailyPeopleTest()
        {
            // TODO unit test for the property 'TargetDailyPeople'
        }

        /// <summary>
        /// Test the property 'OpportunitiesCreated'
        /// </summary>
        [Fact]
        public void OpportunitiesCreatedTest()
        {
            // TODO unit test for the property 'OpportunitiesCreated'
        }

        /// <summary>
        /// Test the property 'MeetingsBooked'
        /// </summary>
        [Fact]
        public void MeetingsBookedTest()
        {
            // TODO unit test for the property 'MeetingsBooked'
        }
    }
}
