/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing EmailTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailTemplate
        //private EmailTemplate instance;

        public EmailTemplateTests()
        {
            // TODO uncomment below to create an instance of EmailTemplate
            //instance = new EmailTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailTemplate
        /// </summary>
        [Fact]
        public void EmailTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailTemplate
            //Assert.IsType<EmailTemplate>(instance);
        }

        /// <summary>
        /// Test the property 'VarEmailTemplate'
        /// </summary>
        [Fact]
        public void VarEmailTemplateTest()
        {
            // TODO unit test for the property 'VarEmailTemplate'
        }
    }
}
