/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing ExternalProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalPropertiesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExternalProperties
        //private ExternalProperties instance;

        public ExternalPropertiesTests()
        {
            // TODO uncomment below to create an instance of ExternalProperties
            //instance = new ExternalProperties();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExternalProperties
        /// </summary>
        [Fact]
        public void ExternalPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExternalProperties
            //Assert.IsType<ExternalProperties>(instance);
        }

        /// <summary>
        /// Test the property 'MaEnabled'
        /// </summary>
        [Fact]
        public void MaEnabledTest()
        {
            // TODO unit test for the property 'MaEnabled'
        }

        /// <summary>
        /// Test the property 'MaDevQaTools'
        /// </summary>
        [Fact]
        public void MaDevQaToolsTest()
        {
            // TODO unit test for the property 'MaDevQaTools'
        }

        /// <summary>
        /// Test the property 'MaMobileWorkflow'
        /// </summary>
        [Fact]
        public void MaMobileWorkflowTest()
        {
            // TODO unit test for the property 'MaMobileWorkflow'
        }

        /// <summary>
        /// Test the property 'MaDarkMode'
        /// </summary>
        [Fact]
        public void MaDarkModeTest()
        {
            // TODO unit test for the property 'MaDarkMode'
        }

        /// <summary>
        /// Test the property 'HotLeads'
        /// </summary>
        [Fact]
        public void HotLeadsTest()
        {
            // TODO unit test for the property 'HotLeads'
        }

        /// <summary>
        /// Test the property 'PeopleCrudAllowCreate'
        /// </summary>
        [Fact]
        public void PeopleCrudAllowCreateTest()
        {
            // TODO unit test for the property 'PeopleCrudAllowCreate'
        }

        /// <summary>
        /// Test the property 'PeopleCrudAllowDelete'
        /// </summary>
        [Fact]
        public void PeopleCrudAllowDeleteTest()
        {
            // TODO unit test for the property 'PeopleCrudAllowDelete'
        }

        /// <summary>
        /// Test the property 'LinkedinOauthFlow'
        /// </summary>
        [Fact]
        public void LinkedinOauthFlowTest()
        {
            // TODO unit test for the property 'LinkedinOauthFlow'
        }
    }
}
