/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing IncludeSignature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IncludeSignatureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IncludeSignature
        //private IncludeSignature instance;

        public IncludeSignatureTests()
        {
            // TODO uncomment below to create an instance of IncludeSignature
            //instance = new IncludeSignature();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IncludeSignature
        /// </summary>
        [Fact]
        public void IncludeSignatureInstanceTest()
        {
            // TODO uncomment below to test "IsType" IncludeSignature
            //Assert.IsType<IncludeSignature>(instance);
        }

        /// <summary>
        /// Test the property 'VarIncludeSignature'
        /// </summary>
        [Fact]
        public void VarIncludeSignatureTest()
        {
            // TODO unit test for the property 'VarIncludeSignature'
        }
    }
}
