/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Note
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NoteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Note
        //private Note instance;

        public NoteTests()
        {
            // TODO uncomment below to create an instance of Note
            //instance = new Note();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Note
        /// </summary>
        [Fact]
        public void NoteInstanceTest()
        {
            // TODO uncomment below to test "IsType" Note
            //Assert.IsType<Note>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'AssociatedType'
        /// </summary>
        [Fact]
        public void AssociatedTypeTest()
        {
            // TODO unit test for the property 'AssociatedType'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'AssociatedWith'
        /// </summary>
        [Fact]
        public void AssociatedWithTest()
        {
            // TODO unit test for the property 'AssociatedWith'
        }

        /// <summary>
        /// Test the property 'Call'
        /// </summary>
        [Fact]
        public void CallTest()
        {
            // TODO unit test for the property 'Call'
        }
    }
}
