/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing PeopleCustomProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PeopleCustomPropertiesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PeopleCustomProperties
        //private PeopleCustomProperties instance;

        public PeopleCustomPropertiesTests()
        {
            // TODO uncomment below to create an instance of PeopleCustomProperties
            //instance = new PeopleCustomProperties();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PeopleCustomProperties
        /// </summary>
        [Fact]
        public void PeopleCustomPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsType" PeopleCustomProperties
            //Assert.IsType<PeopleCustomProperties>(instance);
        }

        /// <summary>
        /// Test the property 'ContactId'
        /// </summary>
        [Fact]
        public void ContactIdTest()
        {
            // TODO unit test for the property 'ContactId'
        }

        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }

        /// <summary>
        /// Test the property 'AllEmailAddresses'
        /// </summary>
        [Fact]
        public void AllEmailAddressesTest()
        {
            // TODO unit test for the property 'AllEmailAddresses'
        }

        /// <summary>
        /// Test the property 'AllPhoneNumbers'
        /// </summary>
        [Fact]
        public void AllPhoneNumbersTest()
        {
            // TODO unit test for the property 'AllPhoneNumbers'
        }

        /// <summary>
        /// Test the property 'AdvanceID'
        /// </summary>
        [Fact]
        public void AdvanceIDTest()
        {
            // TODO unit test for the property 'AdvanceID'
        }
    }
}
