/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing PeoplePostResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PeoplePostResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PeoplePostResponse
        //private PeoplePostResponse instance;

        public PeoplePostResponseTests()
        {
            // TODO uncomment below to create an instance of PeoplePostResponse
            //instance = new PeoplePostResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PeoplePostResponse
        /// </summary>
        [Fact]
        public void PeoplePostResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PeoplePostResponse
            //Assert.IsType<PeoplePostResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
