/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing PeopleCount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PeopleCountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PeopleCount
        //private PeopleCount instance;

        public PeopleCountTests()
        {
            // TODO uncomment below to create an instance of PeopleCount
            //instance = new PeopleCount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PeopleCount
        /// </summary>
        [Fact]
        public void PeopleCountInstanceTest()
        {
            // TODO uncomment below to test "IsType" PeopleCount
            //Assert.IsType<PeopleCount>(instance);
        }

        /// <summary>
        /// Test the property 'People'
        /// </summary>
        [Fact]
        public void PeopleTest()
        {
            // TODO unit test for the property 'People'
        }
    }
}
