/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing PersonCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PersonCreateRequest
        //private PersonCreateRequest instance;

        public PersonCreateRequestTests()
        {
            // TODO uncomment below to create an instance of PersonCreateRequest
            //instance = new PersonCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PersonCreateRequest
        /// </summary>
        [Fact]
        public void PersonCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PersonCreateRequest
            //Assert.IsType<PersonCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }

        /// <summary>
        /// Test the property 'SecondaryEmailAddress'
        /// </summary>
        [Fact]
        public void SecondaryEmailAddressTest()
        {
            // TODO unit test for the property 'SecondaryEmailAddress'
        }

        /// <summary>
        /// Test the property 'PersonalEmailAddress'
        /// </summary>
        [Fact]
        public void PersonalEmailAddressTest()
        {
            // TODO unit test for the property 'PersonalEmailAddress'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'PhoneExtension'
        /// </summary>
        [Fact]
        public void PhoneExtensionTest()
        {
            // TODO unit test for the property 'PhoneExtension'
        }

        /// <summary>
        /// Test the property 'MobilePhone'
        /// </summary>
        [Fact]
        public void MobilePhoneTest()
        {
            // TODO unit test for the property 'MobilePhone'
        }

        /// <summary>
        /// Test the property 'HomePhone'
        /// </summary>
        [Fact]
        public void HomePhoneTest()
        {
            // TODO unit test for the property 'HomePhone'
        }

        /// <summary>
        /// Test the property 'LinkedinUrl'
        /// </summary>
        [Fact]
        public void LinkedinUrlTest()
        {
            // TODO unit test for the property 'LinkedinUrl'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'WorkCity'
        /// </summary>
        [Fact]
        public void WorkCityTest()
        {
            // TODO unit test for the property 'WorkCity'
        }

        /// <summary>
        /// Test the property 'WorkState'
        /// </summary>
        [Fact]
        public void WorkStateTest()
        {
            // TODO unit test for the property 'WorkState'
        }

        /// <summary>
        /// Test the property 'WorkCountry'
        /// </summary>
        [Fact]
        public void WorkCountryTest()
        {
            // TODO unit test for the property 'WorkCountry'
        }

        /// <summary>
        /// Test the property 'PersonCompanyName'
        /// </summary>
        [Fact]
        public void PersonCompanyNameTest()
        {
            // TODO unit test for the property 'PersonCompanyName'
        }

        /// <summary>
        /// Test the property 'PersonCompanyWebsite'
        /// </summary>
        [Fact]
        public void PersonCompanyWebsiteTest()
        {
            // TODO unit test for the property 'PersonCompanyWebsite'
        }

        /// <summary>
        /// Test the property 'PersonCompanyIndustry'
        /// </summary>
        [Fact]
        public void PersonCompanyIndustryTest()
        {
            // TODO unit test for the property 'PersonCompanyIndustry'
        }

        /// <summary>
        /// Test the property 'JobSeniority'
        /// </summary>
        [Fact]
        public void JobSeniorityTest()
        {
            // TODO unit test for the property 'JobSeniority'
        }

        /// <summary>
        /// Test the property 'DoNotContact'
        /// </summary>
        [Fact]
        public void DoNotContactTest()
        {
            // TODO unit test for the property 'DoNotContact'
        }

        /// <summary>
        /// Test the property 'PersonalWebsite'
        /// </summary>
        [Fact]
        public void PersonalWebsiteTest()
        {
            // TODO unit test for the property 'PersonalWebsite'
        }

        /// <summary>
        /// Test the property 'TwitterHandle'
        /// </summary>
        [Fact]
        public void TwitterHandleTest()
        {
            // TODO unit test for the property 'TwitterHandle'
        }
    }
}
