/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing Person
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Person
        //private Person instance;

        public PersonTests()
        {
            // TODO uncomment below to create an instance of Person
            //instance = new Person();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Person
        /// </summary>
        [Fact]
        public void PersonInstanceTest()
        {
            // TODO uncomment below to test "IsType" Person
            //Assert.IsType<Person>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'LastContactedAt'
        /// </summary>
        [Fact]
        public void LastContactedAtTest()
        {
            // TODO unit test for the property 'LastContactedAt'
        }

        /// <summary>
        /// Test the property 'LastRepliedAt'
        /// </summary>
        [Fact]
        public void LastRepliedAtTest()
        {
            // TODO unit test for the property 'LastRepliedAt'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }

        /// <summary>
        /// Test the property 'FullEmailAddress'
        /// </summary>
        [Fact]
        public void FullEmailAddressTest()
        {
            // TODO unit test for the property 'FullEmailAddress'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'HomePhone'
        /// </summary>
        [Fact]
        public void HomePhoneTest()
        {
            // TODO unit test for the property 'HomePhone'
        }

        /// <summary>
        /// Test the property 'MobilePhone'
        /// </summary>
        [Fact]
        public void MobilePhoneTest()
        {
            // TODO unit test for the property 'MobilePhone'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'PersonCompanyWebsite'
        /// </summary>
        [Fact]
        public void PersonCompanyWebsiteTest()
        {
            // TODO unit test for the property 'PersonCompanyWebsite'
        }

        /// <summary>
        /// Test the property 'DoNotContact'
        /// </summary>
        [Fact]
        public void DoNotContactTest()
        {
            // TODO unit test for the property 'DoNotContact'
        }

        /// <summary>
        /// Test the property 'Bouncing'
        /// </summary>
        [Fact]
        public void BouncingTest()
        {
            // TODO unit test for the property 'Bouncing'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

        /// <summary>
        /// Test the property 'LocaleUtcOffset'
        /// </summary>
        [Fact]
        public void LocaleUtcOffsetTest()
        {
            // TODO unit test for the property 'LocaleUtcOffset'
        }

        /// <summary>
        /// Test the property 'EuResident'
        /// </summary>
        [Fact]
        public void EuResidentTest()
        {
            // TODO unit test for the property 'EuResident'
        }

        /// <summary>
        /// Test the property 'PersonalWebsite'
        /// </summary>
        [Fact]
        public void PersonalWebsiteTest()
        {
            // TODO unit test for the property 'PersonalWebsite'
        }

        /// <summary>
        /// Test the property 'LastContactedType'
        /// </summary>
        [Fact]
        public void LastContactedTypeTest()
        {
            // TODO unit test for the property 'LastContactedType'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'SuccessCount'
        /// </summary>
        [Fact]
        public void SuccessCountTest()
        {
            // TODO unit test for the property 'SuccessCount'
        }

        /// <summary>
        /// Test the property 'Starred'
        /// </summary>
        [Fact]
        public void StarredTest()
        {
            // TODO unit test for the property 'Starred'
        }

        /// <summary>
        /// Test the property 'Untouched'
        /// </summary>
        [Fact]
        public void UntouchedTest()
        {
            // TODO unit test for the property 'Untouched'
        }

        /// <summary>
        /// Test the property 'HotLead'
        /// </summary>
        [Fact]
        public void HotLeadTest()
        {
            // TODO unit test for the property 'HotLead'
        }

        /// <summary>
        /// Test the property 'Counts'
        /// </summary>
        [Fact]
        public void CountsTest()
        {
            // TODO unit test for the property 'Counts'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'LastContactedBy'
        /// </summary>
        [Fact]
        public void LastContactedByTest()
        {
            // TODO unit test for the property 'LastContactedBy'
        }

        /// <summary>
        /// Test the property 'Import'
        /// </summary>
        [Fact]
        public void ImportTest()
        {
            // TODO unit test for the property 'Import'
        }

        /// <summary>
        /// Test the property 'PersonStage'
        /// </summary>
        [Fact]
        public void PersonStageTest()
        {
            // TODO unit test for the property 'PersonStage'
        }

        /// <summary>
        /// Test the property 'MostRecentCadence'
        /// </summary>
        [Fact]
        public void MostRecentCadenceTest()
        {
            // TODO unit test for the property 'MostRecentCadence'
        }

        /// <summary>
        /// Test the property 'LastCompletedStepCadence'
        /// </summary>
        [Fact]
        public void LastCompletedStepCadenceTest()
        {
            // TODO unit test for the property 'LastCompletedStepCadence'
        }

        /// <summary>
        /// Test the property 'LastCompletedStep'
        /// </summary>
        [Fact]
        public void LastCompletedStepTest()
        {
            // TODO unit test for the property 'LastCompletedStep'
        }
    }
}
