/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing PersonActivityStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonActivityStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PersonActivityStats
        //private PersonActivityStats instance;

        public PersonActivityStatsTests()
        {
            // TODO uncomment below to create an instance of PersonActivityStats
            //instance = new PersonActivityStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PersonActivityStats
        /// </summary>
        [Fact]
        public void PersonActivityStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PersonActivityStats
            //Assert.IsType<PersonActivityStats>(instance);
        }

        /// <summary>
        /// Test the property 'EmailsSent'
        /// </summary>
        [Fact]
        public void EmailsSentTest()
        {
            // TODO unit test for the property 'EmailsSent'
        }

        /// <summary>
        /// Test the property 'EmailsViewed'
        /// </summary>
        [Fact]
        public void EmailsViewedTest()
        {
            // TODO unit test for the property 'EmailsViewed'
        }

        /// <summary>
        /// Test the property 'EmailsClicked'
        /// </summary>
        [Fact]
        public void EmailsClickedTest()
        {
            // TODO unit test for the property 'EmailsClicked'
        }

        /// <summary>
        /// Test the property 'EmailsRepliedTo'
        /// </summary>
        [Fact]
        public void EmailsRepliedToTest()
        {
            // TODO unit test for the property 'EmailsRepliedTo'
        }

        /// <summary>
        /// Test the property 'EmailsBounced'
        /// </summary>
        [Fact]
        public void EmailsBouncedTest()
        {
            // TODO unit test for the property 'EmailsBounced'
        }

        /// <summary>
        /// Test the property 'Calls'
        /// </summary>
        [Fact]
        public void CallsTest()
        {
            // TODO unit test for the property 'Calls'
        }
    }
}
