/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing QueryResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueryResult
        //private QueryResult instance;

        public QueryResultTests()
        {
            // TODO uncomment below to create an instance of QueryResult
            //instance = new QueryResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueryResult
        /// </summary>
        [Fact]
        public void QueryResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" QueryResult
            //Assert.IsType<QueryResult>(instance);
        }

        /// <summary>
        /// Test the property 'Paging'
        /// </summary>
        [Fact]
        public void PagingTest()
        {
            // TODO unit test for the property 'Paging'
        }

        /// <summary>
        /// Test the property 'Sorting'
        /// </summary>
        [Fact]
        public void SortingTest()
        {
            // TODO unit test for the property 'Sorting'
        }
    }
}
