/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing SharingSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SharingSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SharingSettings
        //private SharingSettings instance;

        public SharingSettingsTests()
        {
            // TODO uncomment below to create an instance of SharingSettings
            //instance = new SharingSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SharingSettings
        /// </summary>
        [Fact]
        public void SharingSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SharingSettings
            //Assert.IsType<SharingSettings>(instance);
        }

        /// <summary>
        /// Test the property 'TeamCadence'
        /// </summary>
        [Fact]
        public void TeamCadenceTest()
        {
            // TODO unit test for the property 'TeamCadence'
        }
    }
}
