/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing SortFilterResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SortFilterResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SortFilterResult
        //private SortFilterResult instance;

        public SortFilterResultTests()
        {
            // TODO uncomment below to create an instance of SortFilterResult
            //instance = new SortFilterResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SortFilterResult
        /// </summary>
        [Fact]
        public void SortFilterResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" SortFilterResult
            //Assert.IsType<SortFilterResult>(instance);
        }

        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Fact]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }

        /// <summary>
        /// Test the property 'SortDirection'
        /// </summary>
        [Fact]
        public void SortDirectionTest()
        {
            // TODO unit test for the property 'SortDirection'
        }
    }
}
