/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing StaticData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StaticDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StaticData
        //private StaticData instance;

        public StaticDataTests()
        {
            // TODO uncomment below to create an instance of StaticData
            //instance = new StaticData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StaticData
        /// </summary>
        [Fact]
        public void StaticDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" StaticData
            //Assert.IsType<StaticData>(instance);
        }

        /// <summary>
        /// Test the property 'VarClient'
        /// </summary>
        [Fact]
        public void VarClientTest()
        {
            // TODO unit test for the property 'VarClient'
        }

        /// <summary>
        /// Test the property 'CrmActivityId'
        /// </summary>
        [Fact]
        public void CrmActivityIdTest()
        {
            // TODO unit test for the property 'CrmActivityId'
        }

        /// <summary>
        /// Test the property 'EmailId'
        /// </summary>
        [Fact]
        public void EmailIdTest()
        {
            // TODO unit test for the property 'EmailId'
        }

        /// <summary>
        /// Test the property 'MailingId'
        /// </summary>
        [Fact]
        public void MailingIdTest()
        {
            // TODO unit test for the property 'MailingId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
    }
}
