/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing StepGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StepGroupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StepGroup
        //private StepGroup instance;

        public StepGroupTests()
        {
            // TODO uncomment below to create an instance of StepGroup
            //instance = new StepGroup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StepGroup
        /// </summary>
        [Fact]
        public void StepGroupInstanceTest()
        {
            // TODO uncomment below to test "IsType" StepGroup
            //Assert.IsType<StepGroup>(instance);
        }

        /// <summary>
        /// Test the property 'Automated'
        /// </summary>
        [Fact]
        public void AutomatedTest()
        {
            // TODO unit test for the property 'Automated'
        }

        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Fact]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }

        /// <summary>
        /// Test the property 'DueImmediately'
        /// </summary>
        [Fact]
        public void DueImmediatelyTest()
        {
            // TODO unit test for the property 'DueImmediately'
        }

        /// <summary>
        /// Test the property 'ReferenceId'
        /// </summary>
        [Fact]
        public void ReferenceIdTest()
        {
            // TODO unit test for the property 'ReferenceId'
        }

        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Fact]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }
    }
}
