/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing TeamTemplateStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamTemplateStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamTemplateStats
        //private TeamTemplateStats instance;

        public TeamTemplateStatsTests()
        {
            // TODO uncomment below to create an instance of TeamTemplateStats
            //instance = new TeamTemplateStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamTemplateStats
        /// </summary>
        [Fact]
        public void TeamTemplateStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" TeamTemplateStats
            //Assert.IsType<TeamTemplateStats>(instance);
        }

        /// <summary>
        /// Test the property 'SentEmails'
        /// </summary>
        [Fact]
        public void SentEmailsTest()
        {
            // TODO unit test for the property 'SentEmails'
        }

        /// <summary>
        /// Test the property 'Views'
        /// </summary>
        [Fact]
        public void ViewsTest()
        {
            // TODO unit test for the property 'Views'
        }

        /// <summary>
        /// Test the property 'Clicks'
        /// </summary>
        [Fact]
        public void ClicksTest()
        {
            // TODO unit test for the property 'Clicks'
        }

        /// <summary>
        /// Test the property 'Replies'
        /// </summary>
        [Fact]
        public void RepliesTest()
        {
            // TODO unit test for the property 'Replies'
        }

        /// <summary>
        /// Test the property 'Bounces'
        /// </summary>
        [Fact]
        public void BouncesTest()
        {
            // TODO unit test for the property 'Bounces'
        }
    }
}
