/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing TeamTemplateSub
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TeamTemplateSubTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TeamTemplateSub
        //private TeamTemplateSub instance;

        public TeamTemplateSubTests()
        {
            // TODO uncomment below to create an instance of TeamTemplateSub
            //instance = new TeamTemplateSub();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TeamTemplateSub
        /// </summary>
        [Fact]
        public void TeamTemplateSubInstanceTest()
        {
            // TODO uncomment below to test "IsType" TeamTemplateSub
            //Assert.IsType<TeamTemplateSub>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'BodyPreview'
        /// </summary>
        [Fact]
        public void BodyPreviewTest()
        {
            // TODO unit test for the property 'BodyPreview'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'LastModifiedAt'
        /// </summary>
        [Fact]
        public void LastModifiedAtTest()
        {
            // TODO unit test for the property 'LastModifiedAt'
        }

        /// <summary>
        /// Test the property 'OpenTrackingEnabled'
        /// </summary>
        [Fact]
        public void OpenTrackingEnabledTest()
        {
            // TODO unit test for the property 'OpenTrackingEnabled'
        }

        /// <summary>
        /// Test the property 'ClickTrackingEnabled'
        /// </summary>
        [Fact]
        public void ClickTrackingEnabledTest()
        {
            // TODO unit test for the property 'ClickTrackingEnabled'
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'Counts'
        /// </summary>
        [Fact]
        public void CountsTest()
        {
            // TODO unit test for the property 'Counts'
        }

        /// <summary>
        /// Test the property 'LastModifiedUser'
        /// </summary>
        [Fact]
        public void LastModifiedUserTest()
        {
            // TODO unit test for the property 'LastModifiedUser'
        }
    }
}
