/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing UpdatePersonResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdatePersonResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdatePersonResponse
        //private UpdatePersonResponse instance;

        public UpdatePersonResponseTests()
        {
            // TODO uncomment below to create an instance of UpdatePersonResponse
            //instance = new UpdatePersonResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdatePersonResponse
        /// </summary>
        [Fact]
        public void UpdatePersonResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdatePersonResponse
            //Assert.IsType<UpdatePersonResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }

        /// <summary>
        /// Test the property 'FullEmailAddress'
        /// </summary>
        [Fact]
        public void FullEmailAddressTest()
        {
            // TODO unit test for the property 'FullEmailAddress'
        }

        /// <summary>
        /// Test the property 'SecondaryEmailAddress'
        /// </summary>
        [Fact]
        public void SecondaryEmailAddressTest()
        {
            // TODO unit test for the property 'SecondaryEmailAddress'
        }

        /// <summary>
        /// Test the property 'PersonalEmailAddress'
        /// </summary>
        [Fact]
        public void PersonalEmailAddressTest()
        {
            // TODO unit test for the property 'PersonalEmailAddress'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'PhoneExtension'
        /// </summary>
        [Fact]
        public void PhoneExtensionTest()
        {
            // TODO unit test for the property 'PhoneExtension'
        }

        /// <summary>
        /// Test the property 'HomePhone'
        /// </summary>
        [Fact]
        public void HomePhoneTest()
        {
            // TODO unit test for the property 'HomePhone'
        }

        /// <summary>
        /// Test the property 'MobilePhone'
        /// </summary>
        [Fact]
        public void MobilePhoneTest()
        {
            // TODO unit test for the property 'MobilePhone'
        }

        /// <summary>
        /// Test the property 'LinkedinUrl'
        /// </summary>
        [Fact]
        public void LinkedinUrlTest()
        {
            // TODO unit test for the property 'LinkedinUrl'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'WorkCity'
        /// </summary>
        [Fact]
        public void WorkCityTest()
        {
            // TODO unit test for the property 'WorkCity'
        }

        /// <summary>
        /// Test the property 'WorkState'
        /// </summary>
        [Fact]
        public void WorkStateTest()
        {
            // TODO unit test for the property 'WorkState'
        }

        /// <summary>
        /// Test the property 'WorkCountry'
        /// </summary>
        [Fact]
        public void WorkCountryTest()
        {
            // TODO unit test for the property 'WorkCountry'
        }

        /// <summary>
        /// Test the property 'PersonCompanyName'
        /// </summary>
        [Fact]
        public void PersonCompanyNameTest()
        {
            // TODO unit test for the property 'PersonCompanyName'
        }

        /// <summary>
        /// Test the property 'PersonCompanyWebsite'
        /// </summary>
        [Fact]
        public void PersonCompanyWebsiteTest()
        {
            // TODO unit test for the property 'PersonCompanyWebsite'
        }

        /// <summary>
        /// Test the property 'PersonCompanyIndustry'
        /// </summary>
        [Fact]
        public void PersonCompanyIndustryTest()
        {
            // TODO unit test for the property 'PersonCompanyIndustry'
        }

        /// <summary>
        /// Test the property 'DoNotContact'
        /// </summary>
        [Fact]
        public void DoNotContactTest()
        {
            // TODO unit test for the property 'DoNotContact'
        }

        /// <summary>
        /// Test the property 'Bouncing'
        /// </summary>
        [Fact]
        public void BouncingTest()
        {
            // TODO unit test for the property 'Bouncing'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

        /// <summary>
        /// Test the property 'LocaleUtcOffset'
        /// </summary>
        [Fact]
        public void LocaleUtcOffsetTest()
        {
            // TODO unit test for the property 'LocaleUtcOffset'
        }

        /// <summary>
        /// Test the property 'EuResident'
        /// </summary>
        [Fact]
        public void EuResidentTest()
        {
            // TODO unit test for the property 'EuResident'
        }

        /// <summary>
        /// Test the property 'PersonalWebsite'
        /// </summary>
        [Fact]
        public void PersonalWebsiteTest()
        {
            // TODO unit test for the property 'PersonalWebsite'
        }

        /// <summary>
        /// Test the property 'TwitterHandle'
        /// </summary>
        [Fact]
        public void TwitterHandleTest()
        {
            // TODO unit test for the property 'TwitterHandle'
        }

        /// <summary>
        /// Test the property 'JobSeniority'
        /// </summary>
        [Fact]
        public void JobSeniorityTest()
        {
            // TODO unit test for the property 'JobSeniority'
        }

        /// <summary>
        /// Test the property 'Untouched'
        /// </summary>
        [Fact]
        public void UntouchedTest()
        {
            // TODO unit test for the property 'Untouched'
        }

        /// <summary>
        /// Test the property 'HotLead'
        /// </summary>
        [Fact]
        public void HotLeadTest()
        {
            // TODO unit test for the property 'HotLead'
        }

        /// <summary>
        /// Test the property 'Counts'
        /// </summary>
        [Fact]
        public void CountsTest()
        {
            // TODO unit test for the property 'Counts'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
    }
}
