/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DawsonSoft.Salesloft.Api.Core.Model;
using DawsonSoft.Salesloft.Api.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DawsonSoft.Salesloft.Api.Core.Test.Model
{
    /// <summary>
    ///  Class for testing User
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for User
        //private User instance;

        public UserTests()
        {
            // TODO uncomment below to create an instance of User
            //instance = new User();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of User
        /// </summary>
        [Fact]
        public void UserInstanceTest()
        {
            // TODO uncomment below to test "IsType" User
            //Assert.IsType<User>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Fact]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'JobRole'
        /// </summary>
        [Fact]
        public void JobRoleTest()
        {
            // TODO unit test for the property 'JobRole'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'VarTimeZone'
        /// </summary>
        [Fact]
        public void VarTimeZoneTest()
        {
            // TODO unit test for the property 'VarTimeZone'
        }

        /// <summary>
        /// Test the property 'LocaleUtcOffset'
        /// </summary>
        [Fact]
        public void LocaleUtcOffsetTest()
        {
            // TODO unit test for the property 'LocaleUtcOffset'
        }

        /// <summary>
        /// Test the property 'SlackUsername'
        /// </summary>
        [Fact]
        public void SlackUsernameTest()
        {
            // TODO unit test for the property 'SlackUsername'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'EmailClientEmailAddress'
        /// </summary>
        [Fact]
        public void EmailClientEmailAddressTest()
        {
            // TODO unit test for the property 'EmailClientEmailAddress'
        }

        /// <summary>
        /// Test the property 'SendingEmailAddress'
        /// </summary>
        [Fact]
        public void SendingEmailAddressTest()
        {
            // TODO unit test for the property 'SendingEmailAddress'
        }

        /// <summary>
        /// Test the property 'FullEmailAddress'
        /// </summary>
        [Fact]
        public void FullEmailAddressTest()
        {
            // TODO unit test for the property 'FullEmailAddress'
        }

        /// <summary>
        /// Test the property 'SeatPackage'
        /// </summary>
        [Fact]
        public void SeatPackageTest()
        {
            // TODO unit test for the property 'SeatPackage'
        }

        /// <summary>
        /// Test the property 'EmailSignature'
        /// </summary>
        [Fact]
        public void EmailSignatureTest()
        {
            // TODO unit test for the property 'EmailSignature'
        }

        /// <summary>
        /// Test the property 'EmailSignatureType'
        /// </summary>
        [Fact]
        public void EmailSignatureTypeTest()
        {
            // TODO unit test for the property 'EmailSignatureType'
        }

        /// <summary>
        /// Test the property 'EmailSignatureClickTrackingDisabled'
        /// </summary>
        [Fact]
        public void EmailSignatureClickTrackingDisabledTest()
        {
            // TODO unit test for the property 'EmailSignatureClickTrackingDisabled'
        }

        /// <summary>
        /// Test the property 'TeamAdmin'
        /// </summary>
        [Fact]
        public void TeamAdminTest()
        {
            // TODO unit test for the property 'TeamAdmin'
        }

        /// <summary>
        /// Test the property 'LocalDialEnabled'
        /// </summary>
        [Fact]
        public void LocalDialEnabledTest()
        {
            // TODO unit test for the property 'LocalDialEnabled'
        }

        /// <summary>
        /// Test the property 'ClickToCallEnabled'
        /// </summary>
        [Fact]
        public void ClickToCallEnabledTest()
        {
            // TODO unit test for the property 'ClickToCallEnabled'
        }

        /// <summary>
        /// Test the property 'EmailClientConfigured'
        /// </summary>
        [Fact]
        public void EmailClientConfiguredTest()
        {
            // TODO unit test for the property 'EmailClientConfigured'
        }

        /// <summary>
        /// Test the property 'CrmConnected'
        /// </summary>
        [Fact]
        public void CrmConnectedTest()
        {
            // TODO unit test for the property 'CrmConnected'
        }

        /// <summary>
        /// Test the property 'ExternalFeatureFlags'
        /// </summary>
        [Fact]
        public void ExternalFeatureFlagsTest()
        {
            // TODO unit test for the property 'ExternalFeatureFlags'
        }

        /// <summary>
        /// Test the property 'PhoneClient'
        /// </summary>
        [Fact]
        public void PhoneClientTest()
        {
            // TODO unit test for the property 'PhoneClient'
        }

        /// <summary>
        /// Test the property 'PhoneNumberAssignment'
        /// </summary>
        [Fact]
        public void PhoneNumberAssignmentTest()
        {
            // TODO unit test for the property 'PhoneNumberAssignment'
        }

        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

        /// <summary>
        /// Test the property 'Team'
        /// </summary>
        [Fact]
        public void TeamTest()
        {
            // TODO unit test for the property 'Team'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
    }
}
