/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DawsonSoft.Salesloft.Api.Core.Client.OpenAPIDateConverter;

namespace DawsonSoft.Salesloft.Api.Core.Model
{
    /// <summary>
    /// ActivityStats
    /// </summary>
    [DataContract(Name = "ActivityStats")]
    public partial class ActivityStats : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityStats" /> class.
        /// </summary>
        /// <param name="attachments">attachments.</param>
        /// <param name="clicks">clicks.</param>
        /// <param name="replies">replies.</param>
        /// <param name="uniqueDevices">uniqueDevices.</param>
        /// <param name="uniqueLocations">uniqueLocations.</param>
        /// <param name="views">views.</param>
        public ActivityStats(int? attachments = default(int?), int? clicks = default(int?), int? replies = default(int?), int? uniqueDevices = default(int?), int? uniqueLocations = default(int?), int? views = default(int?))
        {
            this.Attachments = attachments;
            this.Clicks = clicks;
            this.Replies = replies;
            this.UniqueDevices = uniqueDevices;
            this.UniqueLocations = uniqueLocations;
            this.Views = views;
        }

        /// <summary>
        /// Gets or Sets Attachments
        /// </summary>
        [DataMember(Name = "attachments", EmitDefaultValue = true)]
        public int? Attachments { get; set; }

        /// <summary>
        /// Gets or Sets Clicks
        /// </summary>
        [DataMember(Name = "clicks", EmitDefaultValue = true)]
        public int? Clicks { get; set; }

        /// <summary>
        /// Gets or Sets Replies
        /// </summary>
        [DataMember(Name = "replies", EmitDefaultValue = true)]
        public int? Replies { get; set; }

        /// <summary>
        /// Gets or Sets UniqueDevices
        /// </summary>
        [DataMember(Name = "unique_devices", EmitDefaultValue = true)]
        public int? UniqueDevices { get; set; }

        /// <summary>
        /// Gets or Sets UniqueLocations
        /// </summary>
        [DataMember(Name = "unique_locations", EmitDefaultValue = true)]
        public int? UniqueLocations { get; set; }

        /// <summary>
        /// Gets or Sets Views
        /// </summary>
        [DataMember(Name = "views", EmitDefaultValue = true)]
        public int? Views { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivityStats {\n");
            sb.Append("  Attachments: ").Append(Attachments).Append("\n");
            sb.Append("  Clicks: ").Append(Clicks).Append("\n");
            sb.Append("  Replies: ").Append(Replies).Append("\n");
            sb.Append("  UniqueDevices: ").Append(UniqueDevices).Append("\n");
            sb.Append("  UniqueLocations: ").Append(UniqueLocations).Append("\n");
            sb.Append("  Views: ").Append(Views).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
