/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DawsonSoft.Salesloft.Api.Core.Client.OpenAPIDateConverter;

namespace DawsonSoft.Salesloft.Api.Core.Model
{
    /// <summary>
    /// IncludeSignature
    /// </summary>
    [DataContract(Name = "IncludeSignature")]
    public partial class IncludeSignature : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IncludeSignature" /> class.
        /// </summary>
        /// <param name="varIncludeSignature">varIncludeSignature.</param>
        public IncludeSignature(bool? varIncludeSignature = default(bool?))
        {
            this.VarIncludeSignature = varIncludeSignature;
        }

        /// <summary>
        /// Gets or Sets VarIncludeSignature
        /// </summary>
        [DataMember(Name = "include_signature", EmitDefaultValue = true)]
        public bool? VarIncludeSignature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IncludeSignature {\n");
            sb.Append("  VarIncludeSignature: ").Append(VarIncludeSignature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
