/*
 * Salesloft
 *
 * Salesloft
 *
 * The version of the OpenAPI document: 1.0.alpha
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DawsonSoft.Salesloft.Api.Core.Client.OpenAPIDateConverter;

namespace DawsonSoft.Salesloft.Api.Core.Model
{
    /// <summary>
    /// TeamTemplateStats
    /// </summary>
    [DataContract(Name = "TeamTemplateStats")]
    public partial class TeamTemplateStats : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TeamTemplateStats" /> class.
        /// </summary>
        /// <param name="sentEmails">sentEmails.</param>
        /// <param name="views">views.</param>
        /// <param name="clicks">clicks.</param>
        /// <param name="replies">replies.</param>
        /// <param name="bounces">bounces.</param>
        public TeamTemplateStats(int? sentEmails = default(int?), int? views = default(int?), int? clicks = default(int?), int? replies = default(int?), int? bounces = default(int?))
        {
            this.SentEmails = sentEmails;
            this.Views = views;
            this.Clicks = clicks;
            this.Replies = replies;
            this.Bounces = bounces;
        }

        /// <summary>
        /// Gets or Sets SentEmails
        /// </summary>
        [DataMember(Name = "sent_emails", EmitDefaultValue = true)]
        public int? SentEmails { get; set; }

        /// <summary>
        /// Gets or Sets Views
        /// </summary>
        [DataMember(Name = "views", EmitDefaultValue = true)]
        public int? Views { get; set; }

        /// <summary>
        /// Gets or Sets Clicks
        /// </summary>
        [DataMember(Name = "clicks", EmitDefaultValue = true)]
        public int? Clicks { get; set; }

        /// <summary>
        /// Gets or Sets Replies
        /// </summary>
        [DataMember(Name = "replies", EmitDefaultValue = true)]
        public int? Replies { get; set; }

        /// <summary>
        /// Gets or Sets Bounces
        /// </summary>
        [DataMember(Name = "bounces", EmitDefaultValue = true)]
        public int? Bounces { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TeamTemplateStats {\n");
            sb.Append("  SentEmails: ").Append(SentEmails).Append("\n");
            sb.Append("  Views: ").Append(Views).Append("\n");
            sb.Append("  Clicks: ").Append(Clicks).Append("\n");
            sb.Append("  Replies: ").Append(Replies).Append("\n");
            sb.Append("  Bounces: ").Append(Bounces).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
